### PR TITLE
Update bare-metal providers on overview page

### PR DESCRIPTION
**Pull request by jeremyevans**

### CODE REVIEW

**Review by fdr — COMMENTED** [review]
This is now accurate, and now we don't have to do any sloganeering since it's an easy three elements that keeps it flowing the same. Nevertheless, @ozgune @umurc should be appraised that this inertial bit of text will finally get an update.

**Comment by ozgune** [comment]
Hey @jeremyevans, OVH -> Leaseweb makes a lot of sense. We put in AWS Bare Metal in there primarily because Ubicloud could work on AWS Bare Metal and we wanted to see if we'd get demand for enabling Ubicloud on AWS. I don't have a strong preference for keeping AWS or changing it. (cc @fdr)

**Comment by fdr** [comment]
> Hey @jeremyevans, OVH -> Leaseweb makes a lot of sense. We put in AWS Bare Metal in there primarily because Ubicloud could work on AWS Bare Metal and we wanted to see if we'd get demand for enabling Ubicloud on AWS. I don't have a strong preference for keeping AWS or changing it. (cc @fdr)

Let's change it. The company is more mature now than when the copy was first written, while we could write a somewhat sophisticated AWS integration, it's hard to see exactly why we'd do that.

OVH is fairly normal and it's a bit clearer why and how'd we integrate it, but seeing as we have three live integrations, let's stick to what is there.

**Review by fdr — APPROVED** [review]

**Comment by ozgune** [comment]
Just for information sharing purposes, here's Umur's note on this. Given that we committed the changes, I'm neutral on keeping this as they are vs reverting.

> I'm thinking there might be benefit to keep the AWS Bare Metal still, as it is a much bigger market segment than e.g. Latitude.

> Also, we're in active partnership conversations with Latitude right now. Before we feature them on our home page, I want to see if we can make progress with them

> And perhaps use "now we are featuring you (Latitude) on the home page" as a milestone with them (if we can explore some opportunities more fully) vs. a quick docs change.

**Pull request merged**
