### PR TITLE
Rename screenshot .png files to end in screenshot.png

### PR DESCRIPTION
**Pull request by jeremyevans**
I'll be adding a program to ubicloud to automatically regenerate the screenshots, so I need a consistent file naming scheme for that.

Additionally, fix the Using Kamal with Ubicloud page to use the 3rd screenshot instead of the 2nd screenshot twice.

### CODE REVIEW

**Comment by jeremyevans** [comment]
This also adds the regenerated screenshots, using the program in https://github.com/ubicloud/ubicloud/pull/2097

**Review by fdr — APPROVED** [review]
does the tool do image path checking (so it doesn't render broken links?)

**Comment by jeremyevans** [comment]
> does the tool do image path checking (so it doesn't render broken links?)

It will only replace screenshot files that already exist: https://github.com/ubicloud/ubicloud/pull/2097/files#diff-be6f6de153d373d08ed25811fe0f643a0f2d774b3c4d1522f30544b1fce93c2fR70-R72

**Comment by fdr** [comment]
I meant more like, mintlify, less so the code you wrote. Was wondering if you spotted anything that checks it statically.

**Comment by jeremyevans** [comment]
I don't know about mintlify.  It would be nice if it checked whether the image files that exist are actually referenced (would have caught the 3rd Kamal screenshot issue), but it currently does not appear to.

**Comment by jeremyevans** [comment]
Looks like mintlify does support broken link checking:

```
$ mintlify broken-links
Checking for broken links...

github-actions-integration/price-performance.mdx
  /about/pricing 
  
github-actions-integration/quickstart.mdx
  /about/pricing#github-actions 
  
managed-postgresql/price-performance.mdx
  /about/pricing 
  
security/github-actions.mdx
  /about/security 
  
4 broken links found.
```

Not sure if those links are actually broken.  @enescakir may have ideas?

**Comment by jeremyevans** [comment]
I think those aren't actually broken, they just point to pages outside of `/docs`, which are not in the documentation repository.  Wonder if there is a way to ignore those.

**Comment by jeremyevans** [comment]
I've updated this after latern became available by default, so the managed postgres screenshots show latern.  There is no need for managed-postgresql/flavors.png now, as it has the same content as managed-postgresql/overview-1-screenshot.png, so I switched the paradedb and latern pages to use that.

**Review by fdr — APPROVED** [review]
I like how it kept up with the pricing calculator for Postgres as well, though it makes me realize how much busier things got.

In some cases, it *might* be nice to exclude the navigation bar to make the relevant stuff a bit bigger, but maybe it's also a good cue to show you in what context you'd see that screen.

**Comment by enescakir** [comment]
> Looks like mintlify does support broken link checking:
> 
> ```
> $ mintlify broken-links
> Checking for broken links...
> 
> github-actions-integration/price-performance.mdx
>   /about/pricing 
>   
> github-actions-integration/quickstart.mdx
>   /about/pricing#github-actions 
>   
> managed-postgresql/price-performance.mdx
>   /about/pricing 
>   
> security/github-actions.mdx
>   /about/security 
>   
> 4 broken links found.
> ```
> 
> Not sure if those links are actually broken. @enescakir may have ideas?

Actually they are broken. Since we change our documentation architecture little bit, they are linked to old paths. https://github.com/ubicloud/documentation/commit/267ae93a952411b1e9518e7c5dd02241395f39f9

I fixed them

**Pull request merged**
